
CREATE TABLE BOOKS(
ID INT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
AUTHOR_NAME VARCHAR(20) NOT NULL
)

INSERT INTO BOOKS VALUES(1, 'HARRY POTTER', 'JK ROWLING')

ALTER TABLE BOOKS
ADD COUNT INT CHECK(COUNT>=1)

SELECT * FROM BOOKS

UPDATE BOOKS
SET COUNT=3
WHERE ID=1

CREATE TABLE LIBRARY_VISTOR_USER(
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(20),
AGE INT CHECK(AGE>=17),
EMAIL_ID VARCHAR(20) UNIQUE NOT NULL
)

INSERT INTO LIBRARY_VISTOR_USER(USER_ID, USER_NAME, AGE, EMAIL_ID) 
VALUES(230, 'AKASH', 19, 'abc@xyz.com')

ALTER TABLE LIBRARY_VISTOR_USER
DROP COLUMN EMAIL_ID

ALTER TABLE LIBRARY_VISTOR_USER
ADD COLUMN EMAIL_ID VARCHAR(30) UNIQUE 

UPDATE LIBRARY_VISTOR_USER
SET EMAIL_ID = 'aabbbc@xxyyzz.com'

SELECT * FROM LIBRARY_VISTOR_USER

CREATE TABLE BOOK_ISSUE(
BOOK_ISSUE_ID INT PRIMARY KEY,
BOOK_ID INT REFERENCES BOOKS(ID) NOT NULL,
USER_ID INT REFERENCES LIBRARY_VISTOR_USER(USER_ID) NOT NULL,
BOOK_ISSUE DATE NOT NULL
)

INSERT INTO BOOK_ISSUE(BOOK_ISSUE_ID, BOOK_ID, USER_ID, BOOK_ISSUE)
VALUES(345, 1, 230, '2026-01-09')

SELECT * FROM BOOK_ISSUE

CREATE ROLE LIBRARIAN
WITH LOGIN PASSWORD 'abc@xyz.com'

GRANT SELECT, INSERT, DELETE, UPDATE ON BOOKS TO LIBRARIAN
GRANT SELECT, INSERT, DELETE, UPDATE ON LIBRARY_VISTOR_USER TO LIBRARIAN
GRANT SELECT, INSERT, DELETE, UPDATE ON BOOK_ISSUE TO LIBRARIAN

REVOKE SELECT, INSERT, DELETE, UPDATE ON BOOKS FROM LIBRARIAN
REVOKE SELECT, INSERT, DELETE, UPDATE ON LIBRARY_VISTOR_USER TO LIBRARIAN
REVOKE SELECT, INSERT, DELETE, UPDATE ON BOOK_ISSUE TO LIBRARIAN