INSERT INTO BOOKS VALUES(2, 'POTTER', 'PK JOWLING')

SELECT * FROM BOOKS

INSERT INTO LIBRARY_VISTOR_USER(USER_ID, USER_NAME, AGE, EMAIL_ID) 
VALUES(240, 'KASH', 20, 'bcd@xyz.com')

SELECT * FROM LIBRARY_VISTOR_USER

INSERT INTO BOOK_ISSUE(BOOK_ISSUE_ID, BOOK_ID, USER_ID, BOOK_ISSUE)
VALUES(365, 2, 240, '2026-02-10')

SELECT * FROM BOOK_ISSUE